[project]
name = "e-car"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "OK SEO YUN", email = "okhouse1105@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.4.0",
    "matplotlib>=3.8.0",
    "streamlit>=1.62.0",
]

[project.scripts]
e-car = "e_car:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
